pipeline {
    agent any
    tools {
        jdk 'jdk8'
        maven 'mvn3'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube') {
            steps {
                sh 'mvn sonar:sonar -Dsonar.projectKey=air.quality.metrics -Dsonar.host.url="http://tqs-sonar-qube:9000" -Dsonar.login=e8544bec2705a19e38791482eb9fd52ccd4645b2'
            }
        }
    }
}